name: tofu-new-workspace
description: Create a new OpenTofu workspace
author: Daniel Flook

inputs:
  path:
    description: Path to the OpenTofu configuration
    required: false
    default: .
  workspace:
    description: Name of the OpenTofu workspace
    required: true
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:4c0a6f98ddafa03699d7fb059010f6b5f88d5a8903d1d2e66660ec799de9efad
  entrypoint: /entrypoints/new-workspace.sh

branding:
  icon: globe
  color: purple
